# Generated by Django 4.0.4 on 2022-05-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
